name: Flutter CI/CD

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"
  pull_request:
    branches: ["develop"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.3"
          channel: "stable"
          cache: true

      - name: Cache pubspec dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-

      - name: check version
        run: flutter --version

      - name: build
        run: |
          flutter pub get
          flutter pub run intl_utils:generate
          # flutter pub run build_runner build --delete-conflicting-outputs
          flutter build apk --release
          # flutter build apk --release --split-per-abi

      - name: check changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      # https://github.com/wzieba/Firebase-Distribution-Github-Action
      - name: upload artifact to 'Firebase App Distribution'
        if: contains(steps.changed-files.outputs.all_modified_files, 'RELEASE_NOTES.md')
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: developer-flutter
          releaseNotes: '(F:D) ${{ github.sha }}\n${{ github.event.head_commit.message }}'
          releaseNoteFile: RELEASE_NOTES.md
          file: build/app/outputs/flutter-apk/app-release.apk
        continue-on-error: true

  # iosは保留
  # build_ios:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: subosito/flutter-action@v2
  #     with:
  #       channel: 'stable'
  #       architecture: x64
  #   - run: flutter pub get
  #   - run: flutter test
  #   - run: flutter build ios --release --no-codesign

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.3"
          channel: "stable"
          cache: true

      - name: check version
        run: flutter --version

      - name: Lint
        run: |
          flutter pub run intl_utils:generate
          flutter analyze

      - name: test
        run: |
          mkdir -p build/test-results
          flutter test --machine > build/test-results/results.json

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results/**
